pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Automated Tests') {
            steps {
                dir('backend') {
                    bat 'npm test'
                }
            }
        }
    }
}
