pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('backend') {
                    bat '''
                        set DATABASE_URL=postgresql://postgres:110sumaiya@localhost:5432/campus_thrift
                        npm test
                    '''
                }
            }
        }
    }
}
